In [1]:
from google.colab import files
uploaded=files.upload()

Saving DataSet to DataSet

In [2]:
import pandas as pd
import sqlite3

In [3]:
df=pd.read_csv("DataSet")

In [4]:
conn=sqlite3.connect(':memory:')
df.to_sql('data',conn, index=False)

120588

SQL ANALYSIS

Total Revenue

In [5]:
query="""SELECT SUM(Total_Revenue) AS Total_Revenue FROM data"""
pd.read_sql(query,conn)

   Total_Revenue
0     75713511.0

Revenue by Category

In [6]:
query="""SELECT Category, SUM(Total_Revenue) AS Total_Revenue FROM data  GROUP BY Category ORDER BY Total_Revenue DESC"""
pd.read_sql(query,conn)

        Category  Total_Revenue
0            Set     37846548.0
1          Kurta     20534070.0
2  Western Dress     10642364.0
3            Top      5228091.0
4   Ethnic Dress       762949.0
5         Blouse       438052.0
6         Bottom       140025.0
7          Saree       120802.0
8        Dupatta          610.0

Monthly Revenue

In [7]:
query="""SELECT Month, SUM(Total_Revenue) AS Total_Revenue FROM data GROUP BY Month ORDER BY Month"""
pd.read_sql(query,conn)

   Month  Total_Revenue
0      3        98261.0
1      4     27729278.0
2      5     25206121.0
3      6     22679851.0

Top States by Revenue

In [8]:
query="""SELECT "ship-state", SUM(Total_Revenue) AS Revenue FROM data WHERE Status='Shipped - Delivered To Buyer' GROUP BY "ship-state" ORDER BY Revenue DESC Limit 10"""
pd.read_sql(query,conn)

       ship-state    Revenue
0     Maharashtra  3138053.0
1       Karnataka  2274019.0
2   Uttar Pradesh  1701372.0
3       Telangana  1558387.0
4      Tamil Nadu  1467800.0
5          Kerala  1080435.0
6           Delhi  1041926.0
7  Andhra Pradesh   769416.0
8     West Bengal   749533.0
9         Gujarat   732066.0

Total Orders per Category

In [9]:
query="""SELECT Category, COUNT(*) AS Total_Orders FROM data GROUP BY Category ORDER BY Total_Orders DESC"""
pd.read_sql(query,conn)

        Category  Total_Orders
0            Set         46931
1          Kurta         46374
2  Western Dress         14616
3            Top         10139
4   Ethnic Dress          1093
5         Blouse           873
6         Bottom           412
7          Saree           148
8        Dupatta             2

Total Quantity Sold by Category

In [10]:
query="""SELECT Category, SUM(Qty) AS Total_Quantity FROM data GROUP BY Category ORDER BY Total_Quantity DESC"""
pd.read_sql(query,conn)

        Category  Total_Quantity
0            Set           45115
1          Kurta           44649
2  Western Dress           13854
3            Top            9873
4   Ethnic Dress            1053
5         Blouse             836
6         Bottom             389
7          Saree             145
8        Dupatta               2

Order by Status

In [11]:
query="""SELECT Status, COUNT(*) AS Total_Orders FROM data GROUP BY Status ORDER BY Total_Orders DESC"""
pd.read_sql(query,conn)

                           Status  Total_Orders
0                         Shipped         77282
1    Shipped - Delivered To Buyer         28557
2                       Cancelled         10713
3    Shipped - Returned To Seller          1940
4             Shipped - Picked Up           970
5                         Pending           654
6   Pending - Waiting For Pick Up           277
7   Shipped - Returning To Seller           144
8      Shipped - Out For Delivery            35
9     Shipped - Rejected By Buyer            11
10      Shipped - Lost In Transit             4
11              Shipped - Damaged             1

Average Order Value

In [12]:
import pandas as pd
query="""SELECT AVG(order_total) AS Average_Order_Value FROM ( SELECT "Order ID", SUM(Total_Revenue) AS order_total FROM data WHERE Status='Shipped - Delivered To Buyer' GROUP BY "Order ID")"""
pd.read_sql(query,conn)

   Average_Order_Value
0           704.877857

In [13]:
query="""SELECT AVG(Total_Revenue) AS Average_Order_Value FROM data WHERE Status='Shipped - Delivered To Buyer'"""
pd.read_sql(query,conn)

   Average_Order_Value
0           655.560843

The Average Order value is approximately 655.56